# Generated by Django 3.1.4 on 2021-05-26 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
